name: Bug Report
description: File a bug report
title: "[Fehler]: "
labels: [Fehler]
body:
  - type: markdown
    attributes:
      value: |
        Vielen Dank, dass du dich die Zeit genommen hast, diesen Fehlerbericht auszufüllen!

  - type: textarea
    id: bug-description
    attributes:
      label: Beschreibe den Bug
      description: Eine klare und verständliche Beschreibung des Bugs.
      placeholder: Sag uns, was du siehst!
      value: "Ein Fehler ist passiert! 🙈"
    validations:
      required: true

  - type: textarea
    id: bug-steps
    attributes:
      label: Schritt für Schritt
      description: Schritte, um den Fehler zu reproduzieren.
      placeholder: Wie können wir den Fehler reproduzieren?
      value: |
        1. Gehe zu '...'
        2. Klick auf '....'
        3. Runterscrollen bis '....'
        4. Der Fehler tritt auf
    validations:
      required: true

  - type: textarea
    id: bug-target-state
    attributes:
      label: Soll Zustand
      description: Welches Verhalten oder Zustand wird erwartet?
      placeholder: Wir erwarten ...
      value: "Es soll sein..."
    validations:
      required: true

  - type: textarea
    id: bug-screenshots
    attributes:
      label: Screenshots
      description: Falls notwendig, hier bitte Screenshots oder andere hilfreiche Bilder platzieren.
    validations:
      required: false

  - type: textarea
    id: bug-url
    attributes:
      label: URL
      description: Falls möglich URL des Bugs
      placeholder: ex. https://www.absolventa.de/
    validations:
      required: false

  - type: dropdown
    id: bug-browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - IE
